//// ****** THIS FILE IS AUTOGENERATED ******
////
////          >>>> PLEASE ADAPT IT TO YOUR NEEDS <<<<
////
/// 
///  Filename; C:\Users\Sabrina\PycharmProjects\Instrumentallantz\Practica Especial\final_pid.py
///  Source class: servo_sensor2
///  Generation timestamp: 2019-07-25T11:22:01.117652
///  Class code hash: 2aece2d1e1c6b174ff83a52b98081c3b9099e601
///
/////////////////////////////////////////////////////////////

#include <Arduino.h>
#include "inodriver_user.h"

#include <Servo.h>

Servo myservo;

double PIN_LUZ = A0;

unsigned long last_timestamp;

void user_setup() {
myservo.attach(10);
last_timestamp = 0;
}

void user_loop() {
}

// COMMAND: Angulo, FEAT: angulo

float get_Angulo() {
  return 0.0;
};

int set_Angulo(float value) {
  myservo.write((int)value);
  delay(500);
  return 0;
};


// COMMAND: Brillo, FEAT: intensidad
float get_Brillo() {
  double luz;
  luz = analogRead(PIN_LUZ);
  last_timestamp = millis();
  delay(500);
  return luz;
};

int set_Brillo(float value) {
  return 0;
};


// COMMAND: Tiempo, FEAT: tiempo
float get_Tiempo() {
  return (float)last_timestamp;
};

int set_Tiempo(float value) {
  return 0;
};
